version: "3.1"

services:
    db_principal:
        restart: always
        build: ./db/db_principal
        volumes:
            - "/etc/localtime:/etc/localtime"
        ports:
            - 5434:5432
        env_file: 
            - ./db/db_principal/.db_principal.env
            