version: "3.1"

services:

    # Subindo stancia odoo
    odoo-server:
        build: .
        ports:
            - 80:8069
        depends_on: 
            - db_principal
        environment: 
            - HOST=db_principal
            - USER=postgres_user
            - PASSWORD=postgres_password

    # Subindo instância do postgres
    db_principal:
        restart: always
        build: ./db/db_principal
        volumes:
            - "/etc/localtime:/etc/localtime"
        ports:
            - 5432:5434
        env_file: 
            - "./db/db_principal/.db_principal.env"
    
    # PGAdmin
    pgadmin:
        build: ./db/pgadmin
        ports: 
            - "5051:5051"
        env_file:
            - "./db/pgadmin/.pg4.env"
        links: 
            - db_principal